apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: j9rt8fhaf-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-d1fa424b8b.tsu1.p3.openshiftapps.com/rhtap/rhtap-qe-go:258c9fa9b3d089e28104db0bb5f385c35bfdaf00@sha256:0d1b2d78734b90eed50253926bd406caddd8f387f6b06892c2d30eb530a343bc
          name: container-image
